### ISSUE TITLE
Draw statistics computation

### ISSUE THREAD

**Issue by lionel-panhaleux** [smeea/vtes-db#8]
Love the site ! Thanks for the hard work, it is very useful when trying to put a deck together.

A feature I'd like to see somewhere and I think would match your site propose: a draw statistics calculator. Something where I could put "there, here is my crypt, 5 vamp A, 3 vamp B, 2 vamp C..." and it gives me the probability of occurence of different crypt draws (AABC, AAAB, AAAC, ...)

Maybe just having the probability of "at least one in X draws" would be the most useful, and the same feature for library would be awesome (I have 72 cards, how many Zillah do I need to have > 80% to get one in first hand or first 9-10 cards).

What do you think ?

**Comment by smeea** [comment]
I like the tool like this.
Cannot promise to add it very soon, but maybe this can help as a temporary solution:

**Library draw:**
For this purpose I highly recommend to use hypergeometric calculator, e.g. https://stattrek.com/online-calculator/hypergeometric.aspx
Legend for the one above:
Population size = deck size (i.e. 90 for full deck)
Number of successes in population = how many target cards in deck (i.e. 3 for 3 total zillahs)
Sample size = cards you draw (i.e. 7 for starting hand)
Number of successes in sample = how many cards you are looking for (i.e. 1 if 1 zillah is ok)

**Crypt draw:**
There will be many different (but mostly overlapping) variations to calculate chances for all of them, but if you only need to estimate chances of drawing each particular vampire, you can use same calculation as for Library for each vampire and then just multiplying total chances.
I.e. if in 12 crypt cards:
A is 5 pcs => 92,9% draw chance of at least 1
B is 3 => 74,5%
C is 2 => 57,5%
Then you have 0.929 x 0.745 x 0.575 = 39,8% to draw them all (at least one each), and 69,2% to draw A+B.

**Comment by lionel-panhaleux** [comment]
Thanks for the link !

**Comment by lionel-panhaleux** [comment]
I did a little digging in the mathematics and included a small calculator in the Codex : https://codex-of-the-damned.org/strategy/deck-building.html#stat-form-at-least
